export const Members = [
  {
    id: 0,
    name: "Sammy",
    description: "Founder",
    role: "Founder",
    imageurl: "https://img-appbarber-appbeleza.s3.amazonaws.com/fellasbarbersho-auei%2F127655591722700370699",
    local: "Alameda",
  },
  {
    id: 1,
    name: "José Laylson",
    description: "Owner Partner",
    role: "Owner Partner",
    imageurl: "https://s3-sa-east-1.amazonaws.com/img-appbarber-appbeleza/fellasbarberpre-81lr/6679eb59af887.png",
    local: "Campo Grande",
  },
  {
    id: 2,
    name: "Elias",
    description: "Master Barber",
    role: "Master Barber",
    imageurl: "https://s3-sa-east-1.amazonaws.com/img-appbarber-appbeleza/fellasbarbersho-auei/66a8d006a4600.png",
    local: "Alameda",
  },
  {
    id: 3,
    name: "Gu",
    description: "Master Barber",
    role: "Master Barber",
    imageurl: "https://s3-sa-east-1.amazonaws.com/img-appbarber-appbeleza/fellasbarbersho-auei/66aa43c423ad0.png",
    local: "Alameda",
  },
  {
    id: 4,
    name: "Rodrigo",
    description: "Master Barber",
    role: "Master Barber",
    imageurl: "https://s3-sa-east-1.amazonaws.com/img-appbarber-appbeleza/fellasbarbersho-auei/665de3fe55fc2.png",
    local: "Alameda",
  },
  {
    id: 5,
    name: "Savio",
    description: "Master Barber",
    role: "Master Barber",
    imageurl: "https://s3-sa-east-1.amazonaws.com/img-appbarber-appbeleza/fellasbarbersho-auei/664e48d812dfa.png",
    local: "Alameda",
  },
]